#!/usr/bin/env bash
# ============================================================
# Concurrent SFTTrainer Text-Only training (3 tasks)
# Script mirrors run_train_cls.sh structure.
#
# Output folder naming (auto-built by config_sft.py):
#   outputs/{model}Gen_{date}/
#     method_{FSL|SSP|full}_bs_{bs}_inputdata_input_text_TextOnly_SW{n}/
#       ├── checkpoints/final_model/
#       ├── eval_logs/
#       ├── logs/
#       └── config.json
#
# Usage:
#   bash src_Gen_SFTTrainer/run_sft_text_only.sh
# ============================================================

set -euo pipefail
export PYTHONUNBUFFERED=1

# ============================================================
# !! IMPORTANT PARAMETERS — edit these before launching !!
# ============================================================

# ----- GPU assignment (one physical GPU per task) ----------
GPU_TASK1=0
GPU_TASK2=1
GPU_TASK3=2

# ----- Model names (must match folder names under ~/Documents/LLModel/) -----
MODEL_T1="Qwen3-4B-Instruct-2507"
MODEL_T2="Qwen3-4B-Instruct-2507"
MODEL_T3="llama3.1-8B-Instruct"

# ----- Slide-window size (must match the pkl file generated by preloader) ----
SLIDE_WINDOWS=3

# ----- Batch size per device (reduce if OOM) ---------------------------------
BATCH_T1=2
BATCH_T2=2
BATCH_T3=2

# ----- Gradient accumulation (effective batch = BATCH * GRAD_ACCUM) ----------
GRAD_ACCUM=4

# ----- Learning rate ---------------------------------------------------------
LR=2e-5

# ----- Number of training epochs ---------------------------------------------
EPOCHS=3

# ----- Warmup ratio over total steps -----------------------------------------
WARMUP_RATIO=0.1

# ----- LoRA hyper-parameters -------------------------------------------------
LORA_R=16
LORA_ALPHA=32

# ----- Val / Test split ratios (fraction of TOTAL blocks) --------------------
VAL_RATIO=0.05
TEST_RATIO=0.05

# ----- Paths -----------------------------------------------------------------
DATA_PATH="./data"
OUTPUT_DIR="./outputs"
LOG_DIR="logs/sft_text_only"

# ============================================================
# Shared helpers
# ============================================================

mkdir -p "$LOG_DIR"

ts() { date '+%F %T'; }

pids=()
names=()

start() {
  local name="$1"; shift
  echo "$(ts)  Starting $name ..."
  "$@" >"${LOG_DIR}/${name}.out" 2>&1 &
  pids+=($!)
  names+=("$name")
}

# Move to workspace root so relative paths work
cd "$(dirname "$0")/.."

# ============================================================
# Task 1 — Semi-supervised  (GPU $GPU_TASK1)
# ============================================================
start SSL_SW${SLIDE_WINDOWS}_T1 \
  env CUDA_VISIBLE_DEVICES=$GPU_TASK1 python -m src_Gen_SFTTrainer.train_sft_text_only \
    --cuda_device    $GPU_TASK1       \
    --model_name    "$MODEL_T1"       \
    --data_path      $DATA_PATH       \
    --output_dir     $OUTPUT_DIR      \
    --slide_windows  2   \
    \
    --batch_size               $BATCH_T1   \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --learning_rate            $LR         \
    --num_epochs               $EPOCHS     \
    --warmup_ratio             $WARMUP_RATIO \
    \
    --lora_r     $LORA_R   \
    --lora_alpha $LORA_ALPHA \
    \
    --few_shot                 \
    --shots_per_class 32       \
    --val_ratio   $VAL_RATIO   \
    --test_ratio  $TEST_RATIO  \
    --topic_name "SFT_Qwen_FSL32_SW2" \
    \
    --seed 42 \

    # --semi_supervised          \
    # --semi_ratio  0.1          \

# ============================================================
# Task 2 — Few-shot  (GPU $GPU_TASK2)
# ============================================================
start FSL_SW${SLIDE_WINDOWS}_T2 \
  env CUDA_VISIBLE_DEVICES=$GPU_TASK2 python -m src_Gen_SFTTrainer.train_sft_text_only \
    --cuda_device    $GPU_TASK2       \
    --model_name    "$MODEL_T2"       \
    --data_path      $DATA_PATH       \
    --output_dir     $OUTPUT_DIR      \
    --slide_windows  $SLIDE_WINDOWS   \
    \
    --batch_size               $BATCH_T2   \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --learning_rate            $LR         \
    --num_epochs               $EPOCHS     \
    --warmup_ratio             $WARMUP_RATIO \
    \
    --lora_r     $LORA_R   \
    --lora_alpha $LORA_ALPHA \
    \
    --few_shot                 \
    --shots_per_class 32       \
    --val_ratio   $VAL_RATIO   \
    --test_ratio  $TEST_RATIO  \
    --topic_name "SFT_Qwen_FSL32_SW3" \
    \
    --seed 42

# ============================================================
# Task 3 — Few-shot, different model  (GPU $GPU_TASK3)
# ============================================================
start FSL_SW${SLIDE_WINDOWS}_T3 \
  env CUDA_VISIBLE_DEVICES=$GPU_TASK3 python -m src_Gen_SFTTrainer.train_sft_text_only \
    --cuda_device    $GPU_TASK3       \
    --model_name    "$MODEL_T3"       \
    --data_path      $DATA_PATH       \
    --output_dir     $OUTPUT_DIR      \
    --slide_windows  $SLIDE_WINDOWS   \
    \
    --batch_size               $BATCH_T3   \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --learning_rate            $LR         \
    --num_epochs               $EPOCHS     \
    --warmup_ratio             $WARMUP_RATIO \
    \
    --lora_r     $LORA_R   \
    --lora_alpha $LORA_ALPHA \
    \
    --few_shot                 \
    --shots_per_class 32       \
    --val_ratio   $VAL_RATIO   \
    --test_ratio  $TEST_RATIO  \
    --topic_name "SFT_Llama_FSL32_SW3" \
    \
    --seed 42

# ============================================================
# Cleanly kill children on Ctrl-C / TERM
# ============================================================
trap 'echo; echo "$(ts)  Stopping all jobs..."; kill "${pids[@]}" 2>/dev/null || true' INT TERM

# ============================================================
# Wait for all tasks and report
# ============================================================
echo ""
echo "$(ts)  All 3 tasks launched.  Logs → ${LOG_DIR}/"
echo "$(ts)  PIDs: ${pids[*]}"
echo ""

for i in "${!pids[@]}"; do
  set +e
  wait "${pids[$i]}"
  code=$?
  set -e
  if [[ $code -eq 0 ]]; then
    echo "$(ts)  ${names[$i]}  ✓ finished OK"
  else
    echo "$(ts)  ${names[$i]}  ✗ failed (exit $code) — see ${LOG_DIR}/${names[$i]}.out"
  fi
done

echo ""
echo "$(ts)  All jobs done."
